# SPDX-FileCopyrightText: 2023 Freek van de Ven freek@freekvandeven.nl
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: planet_inspector
description: Flutter planet inspector UI challenge

publish_to: "none"

version: 1.0.0

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  hooks_riverpod: ^2.1.3
  flutter_hooks: ^0.18.5+1
  flutter_cube:
    git:
      url: https://github.com/ueman/flutter_cube
  path: ^1.8.2
  flutter_inset_box_shadow: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.12.0
  flutter_iconica_analysis:
    git:
      url: https://github.com/Iconica-Development/flutter_iconica_analysis
      ref: 4.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/images/
    - assets/planets/
    - assets/planets/earth/
    - assets/planets/mars/
    - assets/planets/mercury/
    - assets/planets/moon/
    - assets/planets/venus/
    - assets/planets/pluto/

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/images/icon.png"
  min_sdk_android: 21